import { renderCopyIcon } from "../../utils/icons.js";
import type { DocumentFeature } from "../types.js";

/** Add copyable Markdown paths to preview headings. */
export function createHeadingCopyFeature(): DocumentFeature {
  const linkIcon =
    '<svg class="action-icon heading-link-icon" viewBox="0 0 20 20" aria-hidden="true"><path d="m8.6 11.4 2.8-2.8"/><path d="M7 14l-1.15 1.15A3 3 0 0 1 1.6 10.9l3-3A3 3 0 0 1 8.85 7"/><path d="m13 6 1.15-1.15A3 3 0 1 1 18.4 9.1l-3 3a3 3 0 0 1-4.25.05"/></svg>';
  const styles = `
.markdown-content :is(h1,h2,h3,h4,h5,h6) .heading-action-button{display:inline-flex;width:28px;height:28px;align-items:center;justify-content:center;margin-left:2px;padding:0;color:var(--fgColor-muted,#59636e);background:transparent;border:0;border-radius:5px;cursor:pointer;opacity:0;visibility:hidden;vertical-align:middle;transition:opacity .12s ease}.markdown-content :is(h1,h2,h3,h4,h5,h6) .heading-copy-button{margin-left:6px}.markdown-content :is(h1,h2,h3,h4,h5,h6):hover .heading-action-button,.markdown-content .heading-action-button:focus-visible{opacity:1;visibility:visible}.markdown-content .heading-action-button:hover{color:var(--fgColor-default,#1f2328);background:var(--button-default-bgColor-hover,#eaeef2)}.markdown-content .heading-action-button:focus-visible{outline:2px solid var(--focus-outlineColor,#0969da);outline-offset:1px}.markdown-content .heading-action-button svg{width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round;stroke-linejoin:round}.markdown-content .heading-action-button .heading-link-icon{stroke-width:2.2}
`;
  const script = `<script>(()=>{
const content=document.querySelector('.markdown-content'),path=content?.dataset.documentPath;if(!content||!path)return;const headings=[...content.querySelectorAll('h1,h2,h3,h4,h5,h6')],ancestors=[];
async function copy(text){if(navigator.clipboard&&window.isSecureContext){try{await navigator.clipboard.writeText(text);return}catch{}}const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.focus();area.select();try{if(!document.execCommand('copy'))throw new Error('コピーに失敗しました')}finally{area.remove()}}
for(const heading of headings){const level=Number(heading.tagName.slice(1)),label=heading.textContent.trim();while(ancestors.length&&ancestors.at(-1).level>=level)ancestors.pop();const value=path+'#'+[...ancestors.map(item=>item.label),label].join('>'),copyButton=document.createElement('button'),linkButton=document.createElement('button');copyButton.type='button';copyButton.className='heading-action-button heading-copy-button';copyButton.dataset.headingPath=value;copyButton.setAttribute('aria-label','見出しパスをコピー');copyButton.title='見出しパスをコピー';copyButton.innerHTML=${JSON.stringify(renderCopyIcon())};copyButton.addEventListener('click',async()=>{try{await copy(value);copyButton.setAttribute('aria-label','見出しパスをコピーしました');copyButton.title='コピーしました'}catch{copyButton.setAttribute('aria-label','見出しパスをコピーできませんでした');copyButton.title='コピーに失敗しました'}setTimeout(()=>{copyButton.setAttribute('aria-label','見出しパスをコピー');copyButton.title='見出しパスをコピー'},1000)});linkButton.type='button';linkButton.className='heading-action-button heading-link-button';linkButton.setAttribute('aria-label','見出しURLをコピー');linkButton.title='見出しURLをコピー';linkButton.innerHTML=${JSON.stringify(linkIcon)};linkButton.addEventListener('click',async()=>{const url=new URL(location.href);url.hash=heading.id;try{await copy(url.href);linkButton.setAttribute('aria-label','見出しURLをコピーしました');linkButton.title='コピーしました'}catch{linkButton.setAttribute('aria-label','見出しURLをコピーできませんでした');linkButton.title='コピーに失敗しました'}setTimeout(()=>{linkButton.setAttribute('aria-label','見出しURLをコピー');linkButton.title='見出しURLをコピー'},1000)});heading.append(copyButton,linkButton);ancestors.push({level,label})}
})()</script>`;
  return { markup: "", styles, script };
}
